name: Pytest

on: [pull_request, workflow_dispatch]

jobs:
  python-pytest:
    name: python-pytest
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@main
      - name: Use Python version 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: Install related python packages
        run: |
          pip install -r requirements.txt

      - name: Pytest unit tests
        id: basic-pytests
        run: |
          pytest  tests/unit --cov="./src" --cov-report=html --cov-report=xml

      - if: ${{ (steps.basic-pytests.outcome == 'success') }}
        name: Upload code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-results
          path: ./htmlcov
